### ISSUE TITLE
Add Uber OSPO case study to the guides

### ISSUE THREAD

**Issue by briankhsieh** [todogroup/todogroup.github.io#124]
Uber's OSPO case study was published as a [blog format.](https://todogroup.org/blog/why-we-run-an-open-source-program-uber/) Please add the case study to the TODO [guides](https://todogroup.org/guides/) under **Open Source Program Case Studies**.  

Thanks.

**Comment by amye** [comment]
@lucperkins, this might be under your landscape?

**Comment by jeffmcaffer** [comment]
Note that the case study shows twice now on the blog page

**Comment by briankhsieh** [comment]
The case study is still not part of the guides page. Anything I can do to help?

**Comment by amye** [comment]
It's listed under Case Studies:
https://github.com/todogroup/todogroup.github.io/blob/master/content/en/guides/casestudies/_index.md

**Comment by briankhsieh** [comment]
Thanks, @amye. Do you know if the list of case studies on this page is actively maintained as well?
https://todogroup.org/guides/

**Comment by amye** [comment]
https://github.com/todogroup/todogroup.github.io/pull/137 is in
