### ISSUE TITLE
Slack link missing on Community page

### ISSUE THREAD

**Issue by ashleywolf** [todogroup/todogroup.github.io#163]
https://todogroup.org/community/

Join us on Slack to chat open source program management: 
<img width="928" alt="Screen Shot 2020-06-05 at 10 40 15 AM" src="https://user-images.githubusercontent.com/10735907/83906733-f59d4580-a718-11ea-9d72-4c5ba1d869d7.png">

**Comment by amye** [comment]
@lucperkins - it's doing that thing again, https://github.com/todogroup/todogroup.github.io/blob/master/content/en/community.md has it but it's not rendering.

**Comment by lucperkins** [comment]
@amye Someone removed the shortcode. Probably a merge issue. I put it back.
