### ISSUE TITLE
Formatting issue in uber use case

### ISSUE THREAD

**Issue by GeorgLink** [todogroup/todogroup.github.io#167]
The first quote in the [Uber use case](https://todogroup.org/guides/casestudies/uber/) has issues with URLs.

![Screen Shot 2020-06-26 at 12 01 15 PM](https://user-images.githubusercontent.com/8862021/85882474-f3bd2400-b7a4-11ea-8242-e7589825e148.png)

I searched for the file that has this content, but didn't see anything wrong with it:
https://github.com/todogroup/todogroup.github.io/edit/master/content/en/blog/open-source-case-studies-uber.md

**Comment by GeorgLink** [comment]
Never mind, I found the correct file and proposed a pr: https://github.com/todogroup/todogroup.github.io/pull/168

**Comment by GeorgLink** [comment]
I'll open this issue again until #165 is merged

**Comment by willnorris** [comment]
Closing, since #165 is now merged.
