### ISSUE TITLE
add a users.md document to summarize the users/OSS projects which use this template

### ISSUE THREAD

**Issue by sums801** [todogroup/todogroup.github.io#18]
add a users.md document , which links to the companies/open source projects , who use this template of open code of conduct

**They may or "may not" be a member of this group, but still they use this template and acknowledge also. List and links of such projects/organizations will be good and positive.**

**Comment by bkeepers** [comment]
Hi @sums801, that's a good suggestion. Currently the list is here: https://github.com/todogroup/opencodeofconduct#what-companies-or-communities-support-or-use-the-open-code-of-conduct

I'm not opposed to adding it to the website.
