### ISSUE TITLE
Blog: Open Source Program Case Studies: Uber page has some issues

### ISSUE THREAD

**Issue by winterrocks** [todogroup/todogroup.github.io#253]
Hi,

- https://todogroup.org/blog/why-we-run-an-open-source-program-uber/ and 
- https://todogroup.org/guides/casestudies/uber/ have the same content (except the top part intro is only on the Blog page)

but https://todogroup.org/blog/why-we-run-an-open-source-program-uber/ has some of the links in the first quotation messed up. 

Maybe it would be a good idea just to have the latter page (case studies) and have all possible links pointing to that page instead of having two pages with almost the same content.

**Comment by anajsana** [comment]
Thanks for this issue @winterrocks 👍 FYI, we are planning to revamp the website this year + we are organizing the use cases by creating a dedicated section in the new OSPO guide: https://landscape.todogroup.org/guide#ospos-in-practice

**Comment by winterrocks** [comment]
Perfect. Just need to remember to put redirect links, etc. so that people will end up on the correct pages.
