### ISSUE TITLE
Issue with RSS

### ISSUE THREAD

**Issue by remyleone** [todogroup/todogroup.github.io#282]
Hello,

I think your RSS feed is not working: https://todogroup.org/feed.xml

**Comment by anajsana** [comment]
Thanks for the heads up @remyleone! We will work on that 👍 Probably it's also time to update the sitemap.xml

**Comment by thetwopct** [comment]
@remyleone We've recently update the website and the RSS feed is back online and working again

https://todogroup.org/index.xml

(The link to the feed is in the footer as the RSS icon too)
