### ISSUE TITLE
Is there a certain "Open-source" maturity model to be included in the Member's list?

### ISSUE THREAD

**Issue by marcellodesales** [todogroup/todogroup.github.io#3]
Hi there,

I'm with Intuit, and we are starting a process of Internal Open-source, which I hope to become more public in the next couple of months... Is there any maturity process that we need to comply so that we can be in the members list?

thanks
Marcello

**Comment by caniszczyk** [comment]
old issue, closing out but you can take a look here: https://github.com/github/maturity-model
