### ISSUE TITLE
Open Source Compliance in the Enterprise link is missing

### ISSUE THREAD

**Issue by CsatariGergely** [todogroup/todogroup.github.io#86]
The document https://todogroup.org/guides/create-program/ in its Policies for compliance refers to a "Open Source Compliance in the Enterprise" what is not linked to the document. 

Also I could not find it in the TODO pages.

**Comment by hyandell** [comment]
It's linked earlier in the text. 

Are links like acronyms where you have to explain them the first time, or do you link them every time? Wikipedia goes with the first time so I can see an argument for not changing this. That said - harmless change :)

**Comment by CsatariGergely** [comment]
I think it is more practical if it is linked every time. We just need to find the correct link as the current one ([previously in the text](https://www.linuxfoundation.org/publications/open-source-compliance-enterprise/)) points to a 404.

**Comment by hyandell** [comment]
Merged. Thank you for all the improvements :)
