### ISSUE TITLE
Move the website to HTTPS

### ISSUE THREAD

**Issue by konklone** [todogroup/todogroup.github.io#9]
Even if it means putting a [free CloudFlare account](https://blog.cloudflare.com/introducing-universal-ssl/) in front of things and [not having it be encrypted end-to-end](https://github.com/isaacs/github/issues/156).

TODO Group represents a bunch of forward thinking companies who do open source, and is angling to play a leadership role in the open source community. When community leaders use HTTPS, it sends a message to the web community.

**Comment by whit537** [comment]
Moreover, the Twitter bio links to https, which leads to [confusion](https://twitter.com/Gratipay/status/841654608183382017) since it's borked.

**Comment by willnorris** [comment]
This actually is a bit embarrassing at this point.  @caniszczyk, is this something LF can help us get setup, since I think they control the DNS at this point.

**Comment by bkeepers** [comment]
This is on GitHub Pages, so I asked our team about getting https enabled for this.

Aside: Pages supports https on `*.github.io` domains, but last I asked about it, support for custom domains hasn't been shipped because the CDN provider doesn't have an automated way to handle key material yet.

**Comment by willnorris** [comment]
@bkeepers: sure, I knew that Pages didn't support custom domains, which was why we would need LF's domain admins to repoint DNS at cloudflare as @konklone suggested.  But if GitHub can manage to do this on your end, that'd be great too. :)

**Comment by caniszczyk** [comment]
@willnorris @bkeepers I emailed LF IT, should take care of it within 24-48 hours, also pegged it as URGENT too.

**Comment by bkeepers** [comment]
@caniszczyk I assigned this to myself and am happy to take care of it. I just need access to DNS, or contact with someone that can make requested changes.

**Comment by lucperkins** [comment]
With the move to Netlify, this issue has been solved: https://todogroup.org

**Comment by caniszczyk** [comment]
Thanks @lucperkins
