### ISSUE TITLE
Open Source Program Office in A Box link is missing

### ISSUE THREAD

**Issue by CsatariGergely** [todogroup/todogroup.github.io#94]
Tools for managing open source programs whitepaper refers to a "Open Source Program Office in A Box" without providing any link.

**Comment by hyandell** [comment]
I think it should probably be deleted. We've discussed this as a cool idea, but apart from having more ideas for things that would go in the box, we don't currently have a box.

**Comment by CsatariGergely** [comment]
It is a cool idea, but we should mention it in the paper once it is on somewhat visible level. I will create a ticket to produce it and remove it from the text.

**Comment by CsatariGergely** [comment]
#100 created.

**Comment by hyandell** [comment]
Merged.
